const DEFAULT_GAME_ENGINE_HOST = process.env.GAME_ENGINE_HOST ?? "localhost";
const DEFAULT_GAME_ENGINE_PORT = process.env.GAME_ENGINE_PORT ?? "3003";
const DEFAULT_GAME_ENGINE_BASE = `http://${DEFAULT_GAME_ENGINE_HOST}:${DEFAULT_GAME_ENGINE_PORT}`;

export const GAME_ENGINE_BASE_URL =
  process.env.GAME_ENGINE_BASE_URL ?? DEFAULT_GAME_ENGINE_BASE;

export const GAME_ENGINE_START_ENDPOINT = `${GAME_ENGINE_BASE_URL}/game-engine/start`;

