GET http://localhost:3001/
Content-Type: application/json

GET http://localhost:3001/auth
Content-Type: application/json

POST http://localhost:3001/
Content-Type: application/json

{
    "username": "usertest",
    "password": "password"
}