GET http://localhost:3001/auth HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 0

###

POST http://localhost:3001/auth/register HTTP/1.1
Host: localhost:3001
Authorization: Basic user:password
Connection: keep-alive
Keep-Alive: timeout=5, max=100
Content-Type: application/json
Content-Length: 0

{
    "username": "username",
    "password": "password",
    "email": "name@gmail.com"
}

###

GET http://localhost:3001/auth/login HTTP/1.1
Host: localhost:3001
Authorization: Basic user:password
Connection: keep-alive
Keep-Alive: timeout=5, max=100
Content-Type: application/json
Content-Length: 0

{
    "username": "username",
    "password": "password",
}
