GET http://localhost:3001/user HTTP/1.1
Host: localhost:3001
Content-Type: application/json
Content-Length: 0

###

POST http://localhost:3001/user HTTP/1.1
Host: localhost:3001
Authorization: Basic user:password
Connection: keep-alive
Keep-Alive: timeout=5, max=100
Content-Type: application/json
Content-Length: 0

{
    "username": "username",
    "email": "email@email.com",
    "password": "password",
}

###

GET http://localhost:3001/user HTTP/1.1
Host: localhost:3001
Authorization: Basic user:password
Connection: keep-alive
Keep-Alive: timeout=5, max=100
Content-Type: application/json
Content-Length: 0

{
    "username": "username",
    "email": "email@email.com",
    "password": "password",
}
